// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ClassLibrary1
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class NurtureFeature : Xunit.IUseFixture<NurtureFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Nurture.feature"
#line hidden
        
        public NurtureFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Nurture", "\nAs a marketer\n  I want to see a site visitor progress\nthough my site directed to" +
                    " the outcome I want", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SetFixture(NurtureFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC1_Open Webinar Nurture plan in the Marketing Control panel")]
        public virtual void Nurture_UC1_OpenWebinarNurturePlanInTheMarketingControlPanel()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC1_Open Webinar Nurture plan in the Marketing Control panel", new string[] {
                        "NeedReview"});
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given("User logged to the Sitecore", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 testRunner.And("Marketing Control Panel is launched", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.When("User expands Engagement Plans section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 12
 testRunner.And("User expands Legal folder", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.And("User selects the Webinar Nurture plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.Then("This shows how a visitor will progress from requesting information to being offer" +
                    "ed access to the legal portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC2_Open Webinar Nurture plan in Supersisor mode")]
        public virtual void Nurture_UC2_OpenWebinarNurturePlanInSupersisorMode()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC2_Open Webinar Nurture plan in Supersisor mode", new string[] {
                        "NeedReview"});
#line 18
this.ScenarioSetup(scenarioInfo);
#line 19
 testRunner.Given("User logged to the Sitecore", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 20
 testRunner.And("Marketing Control Panel is launched", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 21
 testRunner.And("Engagement Plans section is opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 22
 testRunner.And("Legal engagement plan is expanded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 23
 testRunner.When("User selects the Webinar Nurture plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 24
 testRunner.And("User selects Supervise button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 25
 testRunner.Then("this shows which site visitors are in which part of the plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC3_Open Taxation Webinar Information form")]
        public virtual void Nurture_UC3_OpenTaxationWebinarInformationForm()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC3_Open Taxation Webinar Information form", new string[] {
                        "NeedReview"});
#line 29
this.ScenarioSetup(scenarioInfo);
#line 30
 testRunner.Given("Legal website homepage is opened in private browsing session", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 31
 testRunner.When("Actor clicks <Find Out More> link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field"});
            table1.AddRow(new string[] {
                        "Email"});
            table1.AddRow(new string[] {
                        "First Name"});
            table1.AddRow(new string[] {
                        "Last Name"});
#line 32
 testRunner.Then("<Taxation Webinar Information> form with following fields is opened:", ((string)(null)), table1, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC4_Open Taxation Webinar Information form About Us page")]
        public virtual void Nurture_UC4_OpenTaxationWebinarInformationFormAboutUsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC4_Open Taxation Webinar Information form About Us page", new string[] {
                        "NeedReview"});
#line 40
this.ScenarioSetup(scenarioInfo);
#line 41
 testRunner.Given("Legal website homepage is opened in private browsing session", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 42
 testRunner.When("Actor navigates to the /About-Us page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 43
 testRunner.And("Actor clicks <Find Out More> link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field"});
            table2.AddRow(new string[] {
                        "Email"});
            table2.AddRow(new string[] {
                        "First Name"});
            table2.AddRow(new string[] {
                        "Last Name"});
#line 44
 testRunner.Then("<Taxation Webinar Information> form with following fields is opened:", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC5_Submit Taxation Webinar Information form")]
        public virtual void Nurture_UC5_SubmitTaxationWebinarInformationForm()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC5_Submit Taxation Webinar Information form", new string[] {
                        "NeedReview"});
#line 52
this.ScenarioSetup(scenarioInfo);
#line 53
 testRunner.Given("Legal website homepage is opened in private browsing session", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 54
 testRunner.When("Actor clicks <Find Out More> link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "First Name",
                        "Last Name"});
            table3.AddRow(new string[] {
                        "ace5@sitecore.net",
                        "Anna",
                        "Chervonchenko"});
#line 55
 testRunner.And("Actor enters following data in to the <Taxation Webinar Information> form fields", ((string)(null)), table3, "And ");
#line 58
 testRunner.And("Actor clicks <Send Me Information> button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 59
 testRunner.Then("Landing-Pages/Taxation-Webinar/Thank-You page is opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC6_Check Engagement plans section")]
        public virtual void Nurture_UC6_CheckEngagementPlansSection()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC6_Check Engagement plans section", new string[] {
                        "NeedReview"});
#line 63
this.ScenarioSetup(scenarioInfo);
#line 64
 testRunner.Given("Legal website homepage is opened in private browsing session", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 65
 testRunner.When("Actor clicks <Find Out More> link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "First Name",
                        "Last Name"});
            table4.AddRow(new string[] {
                        "ace6@sitecore.net",
                        "Anna",
                        "Chervonchenko"});
#line 66
 testRunner.And("Actor enters following data in to the form fields", ((string)(null)), table4, "And ");
#line 69
 testRunner.And("Actor clicks <Send Me Information> button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 70
 testRunner.And("Actor expands xDB panel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 71
 testRunner.And("Actor expands Engagement section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 72
 testRunner.Then("Engagement plans section contains <Webinar Nurture>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC7_Check Personal Information section")]
        public virtual void Nurture_UC7_CheckPersonalInformationSection()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC7_Check Personal Information section", new string[] {
                        "NeedReview"});
#line 76
this.ScenarioSetup(scenarioInfo);
#line 77
 testRunner.Given("Legal website homepage is opened in private browsing session", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 78
 testRunner.When("Actor clicks <Find Out More> link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "First Name",
                        "Last Name"});
            table5.AddRow(new string[] {
                        "ace7@sitecore.net",
                        "Anna",
                        "Chervonchenko"});
#line 79
 testRunner.And("Actor enters following data in to the form fields", ((string)(null)), table5, "And ");
#line 82
 testRunner.And("Actor clicks <Send Me Information> button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 83
 testRunner.And("Actor expands xDB panel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 84
 testRunner.And("Actor expands Personal Information section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email (Preferred)",
                        "Identification"});
            table6.AddRow(new string[] {
                        "ace7@sitecore.net",
                        "extranet\\ace7_at_sitecore_dot_net"});
#line 85
 testRunner.Then("Personal Information section contains followind data", ((string)(null)), table6, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC8_Check Onsite Behavior section")]
        public virtual void Nurture_UC8_CheckOnsiteBehaviorSection()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC8_Check Onsite Behavior section", new string[] {
                        "NeedReview"});
#line 91
this.ScenarioSetup(scenarioInfo);
#line 92
 testRunner.Given("Legal website homepage is opened in private browsing session", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 93
 testRunner.When("Actor clicks <Find Out More> link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "First Name",
                        "Last Name"});
            table7.AddRow(new string[] {
                        "ace8@sitecore.net",
                        "Anna",
                        "Chervonchenko"});
#line 94
 testRunner.And("Actor enters following data in to the form fields", ((string)(null)), table7, "And ");
#line 97
 testRunner.And("Actor clicks <Send Me Information button>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 98
 testRunner.And("Actor expands xDB panel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 99
 testRunner.And("Actor expands Onsite Behavior section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Legal Persona",
                        "Triggered goals",
                        "Outcomes"});
            table8.AddRow(new string[] {
                        "Lucas the Lawyer",
                        "More Info Legal Webinar",
                        "Contact Acquisition"});
#line 100
 testRunner.Then("following information is present in the section", ((string)(null)), table8, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC9_Check Carousel personalization")]
        public virtual void Nurture_UC9_CheckCarouselPersonalization()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC9_Check Carousel personalization", new string[] {
                        "NeedReview"});
#line 106
this.ScenarioSetup(scenarioInfo);
#line 107
 testRunner.Given("Legal website homepage is opened in private browsing session", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 108
 testRunner.And("Actor clicked <Find Out More> link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "First Name",
                        "Last Name"});
            table9.AddRow(new string[] {
                        "ace9@sitecore.net",
                        "Anna",
                        "Chervonchenko"});
#line 109
 testRunner.And("Actor entered following data in to the form fields", ((string)(null)), table9, "And ");
#line 112
 testRunner.And("Actor clicked <Send Me Information> button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 113
 testRunner.When("Actor navigates to Home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 114
 testRunner.Then("<Register Now> link available in the Carousel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC10_Check registration form pre-population")]
        public virtual void Nurture_UC10_CheckRegistrationFormPre_Population()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC10_Check registration form pre-population", new string[] {
                        "NeedReview"});
#line 118
this.ScenarioSetup(scenarioInfo);
#line 119
 testRunner.Given("Legal website homepage is opened in private browsing session", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 120
 testRunner.And("Actor clicked <Find Out More> link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "First Name",
                        "Last Name"});
            table10.AddRow(new string[] {
                        "ace10@sitecore.net",
                        "Anna",
                        "Chervonchenko"});
#line 121
 testRunner.And("Actor entered following data in to the form fields", ((string)(null)), table10, "And ");
#line 124
 testRunner.And("Actor clicked <Send Me Information button>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 125
 testRunner.When("Actor navigates to Home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 126
 testRunner.And("Actor clicks <Register Now> link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "First Name",
                        "Last Name",
                        "Month Preference"});
            table11.AddRow(new string[] {
                        "ace10@sitecore.net",
                        "Anna",
                        "Chervonchenko",
                        "January"});
#line 127
 testRunner.Then("form fields contain following data", ((string)(null)), table11, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC11_")]
        public virtual void Nurture_UC11_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC11_", new string[] {
                        "NeedReview"});
#line 133
this.ScenarioSetup(scenarioInfo);
#line 134
 testRunner.Given("Legal website is opened on the /Landing-Pages/Taxation-Webinar/Taxation-Webinar-R" +
                    "egister page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "First Name",
                        "Last Name",
                        "Month Preference"});
            table12.AddRow(new string[] {
                        "ace11@sitecore.net",
                        "Anna",
                        "Chervonchenko",
                        "January"});
#line 135
 testRunner.When("Actor enters followind data into form fields", ((string)(null)), table12, "When ");
#line 138
 testRunner.And("Actor clicks <Register Now> button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 139
 testRunner.Then("/Landing-Pages/Taxation-Webinar/Thank-You page is opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC12_")]
        public virtual void Nurture_UC12_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC12_", new string[] {
                        "NeedReview"});
#line 143
this.ScenarioSetup(scenarioInfo);
#line 144
 testRunner.Given("Legal website is opened on the /Landing-Pages/Taxation-Webinar/Taxation-Webinar-R" +
                    "egister page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "First Name",
                        "Last Name",
                        "Month Preference"});
            table13.AddRow(new string[] {
                        "ace12@sitecore.net",
                        "Anna",
                        "Chervonchenko",
                        "January"});
#line 145
 testRunner.When("Actor enters followind data into form fields", ((string)(null)), table13, "When ");
#line 148
 testRunner.And("Actor clicks <Register Now> button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 149
 testRunner.And("Actor expands xDB panel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 150
 testRunner.And("Actor expands Onsite Behavior section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Triggered goals",
                        "Outcomes"});
            table14.AddRow(new string[] {
                        "Registered Legal Webinar",
                        "Marketing Lead"});
#line 151
 testRunner.Then("following information is present in the section", ((string)(null)), table14, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC13_")]
        public virtual void Nurture_UC13_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC13_", new string[] {
                        "NeedReview"});
#line 156
this.ScenarioSetup(scenarioInfo);
#line 157
testRunner.Given("Legal website is opened on the /Landing-Pages/Taxation-Webinar/Taxation-Webinar-R" +
                    "egister page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "First Name",
                        "Last Name",
                        "Month Preference"});
            table15.AddRow(new string[] {
                        "ace12@sitecore.net",
                        "Anna",
                        "Chervonchenko",
                        "January"});
#line 158
 testRunner.When("Actor enters followind data into form fields", ((string)(null)), table15, "When ");
#line 161
 testRunner.And("Actor clicks <Register Now> button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 162
 testRunner.And("Actor expands xDB panel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 163
 testRunner.And("Actor expands Onsite Behavior section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Triggered goals",
                        "Outcomes"});
            table16.AddRow(new string[] {
                        "Registered Legal Webinar",
                        "Marketing Lead"});
#line 164
 testRunner.Then("following information is present in the section", ((string)(null)), table16, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                NurtureFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                NurtureFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
