// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ClassLibrary1
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "UI")]
    public partial class NurtureFeature : Xunit.IClassFixture<NurtureFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Nurture.feature"
#line hidden
        
        public NurtureFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Nurture", "\tAs a marketer\r\n    I want to see a site visitor progress\r\n\tthough my site direct" +
                    "ed to the outcome I want", ProgrammingLanguage.CSharp, new string[] {
                        "UI"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SetFixture(NurtureFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="Nurture_UC1_Open Webinar Nurture plan in the Marketing Control panel")]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC1_Open Webinar Nurture plan in the Marketing Control panel")]
        [Xunit.TraitAttribute("Category", "OnlyManual")]
        public virtual void Nurture_UC1_OpenWebinarNurturePlanInTheMarketingControlPanel()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC1_Open Webinar Nurture plan in the Marketing Control panel", new string[] {
                        "OnlyManual"});
#line 9
this.ScenarioSetup(scenarioInfo);
#line 10
 testRunner.Given("User logged to the Sitecore as Emma", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 11
 testRunner.And("Marketing Control Panel is launched", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.When("User expands Engagement Plans section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 13
 testRunner.And("User expands Legal folder", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.And("User selects the Webinar Nurture plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Section name",
                        "State",
                        "Title"});
            table1.AddRow(new string[] {
                        "Search",
                        "Registered?",
                        "Requested More Info"});
            table1.AddRow(new string[] {
                        "Register",
                        "Downloaded",
                        "Registered ForWebinar"});
            table1.AddRow(new string[] {
                        "Engaged",
                        "<empty>",
                        "Downloaded Whitepaper"});
#line 15
 testRunner.Then("Webinar Nurture contains following sections", ((string)(null)), table1, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Nurture_UC2_Open Webinar Nurture plan in Supervisor mode")]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC2_Open Webinar Nurture plan in Supervisor mode")]
        [Xunit.TraitAttribute("Category", "OnlyManual")]
        public virtual void Nurture_UC2_OpenWebinarNurturePlanInSupervisorMode()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC2_Open Webinar Nurture plan in Supervisor mode", new string[] {
                        "OnlyManual"});
#line 23
this.ScenarioSetup(scenarioInfo);
#line 24
 testRunner.Given("User logged to the Sitecore as Emma", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 25
 testRunner.And("Marketing Control Panel is launched", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
 testRunner.And("Engagement Plans section is opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
 testRunner.And("Legal engagement plan is expanded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 28
 testRunner.When("User selects the Webinar Nurture plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 29
 testRunner.And("User selects Supervise button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
 testRunner.Then("Then Supervisor window has opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 31
    testRunner.And("System shows 0% for each state", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Nurture_UC3_Open Taxation Webinar Information form")]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC3_Open Taxation Webinar Information form")]
        [Xunit.TraitAttribute("Category", "Ready")]
        public virtual void Nurture_UC3_OpenTaxationWebinarInformationForm()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC3_Open Taxation Webinar Information form", new string[] {
                        "Ready"});
#line 35
this.ScenarioSetup(scenarioInfo);
#line 36
 testRunner.Given("Legal website homepage is opened in private browsing session", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 37
 testRunner.When("Actor clicks Find Out More link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field"});
            table2.AddRow(new string[] {
                        "Email"});
            table2.AddRow(new string[] {
                        "First Name"});
            table2.AddRow(new string[] {
                        "Last Name"});
#line 38
 testRunner.Then("Taxation Webinar Information form with following fields is opened:", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Nurture_UC4_Open Taxation Webinar Information form About Us page")]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC4_Open Taxation Webinar Information form About Us page")]
        [Xunit.TraitAttribute("Category", "Ready")]
        public virtual void Nurture_UC4_OpenTaxationWebinarInformationFormAboutUsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC4_Open Taxation Webinar Information form About Us page", new string[] {
                        "Ready"});
#line 46
this.ScenarioSetup(scenarioInfo);
#line 47
 testRunner.Given("Legal website homepage is opened in private browsing session", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 48
 testRunner.When("Actor navigates to the About-Us page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 49
 testRunner.And("Actor clicks Find Out More link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field"});
            table3.AddRow(new string[] {
                        "Email"});
            table3.AddRow(new string[] {
                        "First Name"});
            table3.AddRow(new string[] {
                        "Last Name"});
#line 50
 testRunner.Then("Taxation Webinar Information form with following fields is opened:", ((string)(null)), table3, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Nurture_UC5_Submit Taxation Webinar Information form")]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC5_Submit Taxation Webinar Information form")]
        [Xunit.TraitAttribute("Category", "Ready")]
        public virtual void Nurture_UC5_SubmitTaxationWebinarInformationForm()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC5_Submit Taxation Webinar Information form", new string[] {
                        "Ready"});
#line 58
this.ScenarioSetup(scenarioInfo);
#line 59
 testRunner.Given("Legal website homepage is opened in private browsing session", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 60
 testRunner.When("Actor clicks Find Out More link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "First Name",
                        "Last Name"});
            table4.AddRow(new string[] {
                        "ace5@sitecore.net",
                        "Anna",
                        "Chervonchenko"});
#line 61
 testRunner.And("Actor enters following data in to the Taxation Webinar Information form fields", ((string)(null)), table4, "And ");
#line 64
 testRunner.And("Actor clicks Send Me Information button on form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 65
 testRunner.Then("Landing-Pages/Taxation-Webinar/Thank-You page is opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 66
    testRunner.And("Thank You title presents", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Text"});
            table5.AddRow(new string[] {
                        "Our servers are processing your request now. As soon as your request has been pro" +
                            "cessed, we will send a confirmation email to the address you supplied."});
#line 67
 testRunner.And("Following registration text presents:", ((string)(null)), table5, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Nurture_UC6_Check Engagement plans section")]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC6_Check Engagement plans section")]
        [Xunit.TraitAttribute("Category", "Ready")]
        public virtual void Nurture_UC6_CheckEngagementPlansSection()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC6_Check Engagement plans section", new string[] {
                        "Ready"});
#line 73
this.ScenarioSetup(scenarioInfo);
#line 74
 testRunner.Given("Legal website homepage is opened in private browsing session", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 75
 testRunner.When("Actor clicks Find Out More link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "First Name",
                        "Last Name"});
            table6.AddRow(new string[] {
                        "ace6@sitecore.net",
                        "Anna",
                        "Chervonchenko"});
#line 76
 testRunner.And("Actor enters following data in to the Taxation Webinar Information form fields", ((string)(null)), table6, "And ");
#line 79
 testRunner.And("Actor clicks Send Me Information button on form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 80
 testRunner.And("Actor selects Open visit details panel slidebar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 81
 testRunner.And("Actor expands Engagement header on xDB panel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 82
 testRunner.Then("Engagement plans section contains Webinar Nurture", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 83
 testRunner.And("Engagement plan sate equals to Requested More Info", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Nurture_UC7_Check Personal Information section")]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC7_Check Personal Information section")]
        [Xunit.TraitAttribute("Category", "Ready")]
        public virtual void Nurture_UC7_CheckPersonalInformationSection()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC7_Check Personal Information section", new string[] {
                        "Ready"});
#line 87
this.ScenarioSetup(scenarioInfo);
#line 88
 testRunner.Given("Legal website homepage is opened in private browsing session", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 89
 testRunner.When("Actor clicks Find Out More link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "First Name",
                        "Last Name"});
            table7.AddRow(new string[] {
                        "ace7@sitecore.net",
                        "Anna",
                        "Chervonchenko"});
#line 90
 testRunner.And("Actor enters following data in to the Taxation Webinar Information form fields", ((string)(null)), table7, "And ");
#line 93
 testRunner.And("Actor clicks Send Me Information button on form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 94
 testRunner.And("Actor selects Open visit details panel slidebar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 95
 testRunner.And("Actor expands Personal Information header on xDB panel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Data"});
            table8.AddRow(new string[] {
                        "ace7@sitecore.net"});
            table8.AddRow(new string[] {
                        "extranet\\ace7_at_sitecore_dot_net"});
#line 96
 testRunner.Then("Personal Information section contains followind data", ((string)(null)), table8, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Nurture_UC8_Check Onsite Behavior section")]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC8_Check Onsite Behavior section")]
        [Xunit.TraitAttribute("Category", "Ready")]
        public virtual void Nurture_UC8_CheckOnsiteBehaviorSection()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC8_Check Onsite Behavior section", new string[] {
                        "Ready"});
#line 103
this.ScenarioSetup(scenarioInfo);
#line 104
 testRunner.Given("Legal website homepage is opened in private browsing session", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 105
 testRunner.When("Actor clicks Find Out More link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "First Name",
                        "Last Name"});
            table9.AddRow(new string[] {
                        "ace8@sitecore.net",
                        "Anna",
                        "Chervonchenko"});
#line 106
 testRunner.And("Actor enters following data in to the Taxation Webinar Information form fields", ((string)(null)), table9, "And ");
#line 109
 testRunner.And("Actor clicks Send Me Information button on form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 110
 testRunner.And("Actor selects Open visit details panel slidebar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 111
 testRunner.And("Actor expands Onsite Behavior header on xDB panel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Legal Persona",
                        "Triggered goals",
                        "Outcomes"});
            table10.AddRow(new string[] {
                        "Lucas the Lawyer",
                        "More Info Legal Webinar",
                        "Contact Acquisition"});
#line 112
 testRunner.Then("Following information is present in the section", ((string)(null)), table10, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Nurture_UC9_Check Carousel personalization")]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC9_Check Carousel personalization")]
        [Xunit.TraitAttribute("Category", "Ready")]
        public virtual void Nurture_UC9_CheckCarouselPersonalization()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC9_Check Carousel personalization", new string[] {
                        "Ready"});
#line 118
this.ScenarioSetup(scenarioInfo);
#line 119
 testRunner.Given("Legal website homepage is opened in private browsing session", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 120
 testRunner.And("Actor clicked Find Out More link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "First Name",
                        "Last Name"});
            table11.AddRow(new string[] {
                        "ace9@sitecore.net",
                        "Anna",
                        "Chervonchenko"});
#line 121
 testRunner.And("Actor enters following data in to the Taxation Webinar Information form fields", ((string)(null)), table11, "And ");
#line 124
 testRunner.And("Actor clicked Send Me Information button on form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 125
 testRunner.When("Actor navigates to Home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 126
 testRunner.Then("Register Now link available in the Carousel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Nurture_UC10_Check registration form pre-population")]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC10_Check registration form pre-population")]
        [Xunit.TraitAttribute("Category", "Ready")]
        public virtual void Nurture_UC10_CheckRegistrationFormPre_Population()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC10_Check registration form pre-population", new string[] {
                        "Ready"});
#line 130
this.ScenarioSetup(scenarioInfo);
#line 131
 testRunner.Given("Legal website homepage is opened in private browsing session", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 132
 testRunner.And("Actor clicked Find Out More link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "First Name",
                        "Last Name"});
            table12.AddRow(new string[] {
                        "ace10@sitecore.net",
                        "Anna",
                        "Chervonchenko"});
#line 133
 testRunner.And("Actor enters following data in to the Taxation Webinar Information form fields", ((string)(null)), table12, "And ");
#line 136
 testRunner.And("Actor clicked Send Me Information button on form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 137
 testRunner.When("Actor navigates to Home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 138
 testRunner.And("Actor clicks Register Now button on Carousel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "First Name",
                        "Last Name",
                        "Month Preference"});
            table13.AddRow(new string[] {
                        "ace10@sitecore.net",
                        "Anna",
                        "Chervonchenko",
                        "January"});
#line 139
 testRunner.Then("Taxation Webinar Register form fields contain following data", ((string)(null)), table13, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Nurture_UC11_Register now")]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC11_Register now")]
        [Xunit.TraitAttribute("Category", "Ready")]
        public virtual void Nurture_UC11_RegisterNow()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC11_Register now", new string[] {
                        "Ready"});
#line 145
this.ScenarioSetup(scenarioInfo);
#line 146
 testRunner.Given("Legal website is opened on the Taxation-Webinar-Register page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "First Name",
                        "Last Name"});
            table14.AddRow(new string[] {
                        "ace11@sitecore.net",
                        "Anna",
                        "Chervonchenko"});
#line 147
 testRunner.When("Actor enters followind data into form fields", ((string)(null)), table14, "When ");
#line 150
 testRunner.And("Actor sets Month Preference combobox to May", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 151
 testRunner.And("Actor clicks Register Now button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 152
 testRunner.Then("en/Landing-Pages/Taxation-Webinar/Thank-You page is opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 153
 testRunner.And("Thank You title presents", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Text"});
            table15.AddRow(new string[] {
                        "Our servers are processing your request now. As soon as your request has been pro" +
                            "cessed, we will send a confirmation email to the address you supplied."});
#line 154
 testRunner.And("Following registration text presents:", ((string)(null)), table15, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Nurture_UC12_Trigger outcomes on registration")]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC12_Trigger outcomes on registration")]
        [Xunit.TraitAttribute("Category", "Ready")]
        public virtual void Nurture_UC12_TriggerOutcomesOnRegistration()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC12_Trigger outcomes on registration", new string[] {
                        "Ready"});
#line 160
this.ScenarioSetup(scenarioInfo);
#line 161
 testRunner.Given("Legal website is opened on the Taxation-Webinar-Register page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "First Name",
                        "Last Name"});
            table16.AddRow(new string[] {
                        "ace12@sitecore.net",
                        "Anna",
                        "Chervonchenko"});
#line 162
 testRunner.When("Actor enters followind data into form fields", ((string)(null)), table16, "When ");
#line 165
 testRunner.And("Actor clicks Register Now button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 166
 testRunner.And("Actor selects Open visit details panel slidebar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 167
 testRunner.And("Actor expands Onsite Behavior header on xDB panel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Triggered goals",
                        "Outcomes"});
            table17.AddRow(new string[] {
                        "Registered Legal Webinar",
                        "Marketing Lead"});
#line 168
 testRunner.Then("Following information is present in the section", ((string)(null)), table17, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Nurture_UC13_Download whitepaper")]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC13_Download whitepaper")]
        [Xunit.TraitAttribute("Category", "Ready")]
        public virtual void Nurture_UC13_DownloadWhitepaper()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC13_Download whitepaper", new string[] {
                        "Ready"});
#line 175
this.ScenarioSetup(scenarioInfo);
#line 176
 testRunner.Given("Legal website is opened on the Taxation-Webinar-Register page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "First Name",
                        "Last Name"});
            table18.AddRow(new string[] {
                        "ace11@sitecore.net",
                        "Anna",
                        "Chervonchenko"});
#line 177
 testRunner.And("Actor enters followind data into form fields", ((string)(null)), table18, "And ");
#line 180
 testRunner.And("Actor sets Month Preference combobox to May", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 181
 testRunner.And("Actor clicks Register Now button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 182
 testRunner.And("Actor navigates to Home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 183
 testRunner.When("Actor clicks Download Now link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 184
 testRunner.And("Actor selects Open visit details panel slidebar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 185
 testRunner.And("Actor clicks Refresh button on xDB panel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 186
 testRunner.And("Actor expands Onsite Behavior header on xDB panel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Triggered goals"});
            table19.AddRow(new string[] {
                        "Download White Paper Legal Webinar"});
#line 187
 testRunner.Then("Following information is present in the section", ((string)(null)), table19, "Then ");
#line 190
 testRunner.And("Download White Paper Legal Webinar goal contains value 20 points", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Nurture_UC14_Alternate demo path. Email mock-up page. Check personalized info pag" +
            "e")]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC14_Alternate demo path. Email mock-up page. Check personalized info pag" +
            "e")]
        [Xunit.TraitAttribute("Category", "Ready")]
        public virtual void Nurture_UC14_AlternateDemoPath_EmailMock_UpPage_CheckPersonalizedInfoPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC14_Alternate demo path. Email mock-up page. Check personalized info pag" +
                    "e", new string[] {
                        "Ready"});
#line 195
this.ScenarioSetup(scenarioInfo);
#line 196
 testRunner.Given("Legal website is opened on the Legal/Email page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 197
 testRunner.When("Actor clicks Register now link on Legal/Email page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 198
 testRunner.Then("Page URL contains sc_camp=356A7E5445E14860AFBBF922E8A3018F", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field"});
            table20.AddRow(new string[] {
                        "Email"});
            table20.AddRow(new string[] {
                        "First Name"});
            table20.AddRow(new string[] {
                        "Last Name"});
            table20.AddRow(new string[] {
                        "Month Preference"});
#line 199
    testRunner.And("Taxation Webinar Register form with following fields is opened:", ((string)(null)), table20, "And ");
#line 205
 testRunner.And("Register Now button presents on the page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Nurture_UC15_Alternate demo path. Email mock-up page. Verify xDB panel")]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC15_Alternate demo path. Email mock-up page. Verify xDB panel")]
        [Xunit.TraitAttribute("Category", "Ready")]
        public virtual void Nurture_UC15_AlternateDemoPath_EmailMock_UpPage_VerifyXDBPanel()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC15_Alternate demo path. Email mock-up page. Verify xDB panel", new string[] {
                        "Ready"});
#line 209
this.ScenarioSetup(scenarioInfo);
#line 210
 testRunner.Given("Legal website is opened on the Legal/Email page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 211
 testRunner.When("Actor clicks Register now link on Legal/Email page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 212
 testRunner.And("Actor selects Open visit details panel slidebar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 213
 testRunner.And("Actor expands Referral header on xDB panel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field values"});
            table21.AddRow(new string[] {
                        "Active"});
            table21.AddRow(new string[] {
                        "Email Legal Webinar"});
            table21.AddRow(new string[] {
                        "Online/Email campaigns/Email marketing"});
#line 214
 testRunner.Then("Following information is present in the Campaigns section:", ((string)(null)), table21, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Nurture_UC16_Alternate demo path. Facebook campaign. Check personalized info page" +
            "")]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC16_Alternate demo path. Facebook campaign. Check personalized info page" +
            "")]
        [Xunit.TraitAttribute("Category", "OnlyManual")]
        public virtual void Nurture_UC16_AlternateDemoPath_FacebookCampaign_CheckPersonalizedInfoPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC16_Alternate demo path. Facebook campaign. Check personalized info page" +
                    "", new string[] {
                        "OnlyManual"});
#line 222
this.ScenarioSetup(scenarioInfo);
#line 223
 testRunner.Given("Facebook website is opened on the https://www.facebook.com/ridleysc/ page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 224
 testRunner.When("Actor clicks link with sc_camp=23A9161A0CA847ACB718D100B65A1328", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field"});
            table22.AddRow(new string[] {
                        "Email"});
            table22.AddRow(new string[] {
                        "First Name"});
            table22.AddRow(new string[] {
                        "Last Name"});
#line 225
    testRunner.Then("<Taxation Webinar Information> form with following fields is opened", ((string)(null)), table22, "Then ");
#line 230
 testRunner.And("<Send Me Information> button presents on the page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 231
 testRunner.And("Title contains <Taxation Webinar Information>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Nurture_UC17_Alternate demo path. Facebook campaign. Verify xDB panel")]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC17_Alternate demo path. Facebook campaign. Verify xDB panel")]
        [Xunit.TraitAttribute("Category", "OnlyManual")]
        public virtual void Nurture_UC17_AlternateDemoPath_FacebookCampaign_VerifyXDBPanel()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC17_Alternate demo path. Facebook campaign. Verify xDB panel", new string[] {
                        "OnlyManual"});
#line 235
this.ScenarioSetup(scenarioInfo);
#line 236
 testRunner.Given("Facebook website is opened on the https://www.facebook.com/ridleysc/ page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 237
 testRunner.When("Actor clicks link with sc_camp=23A9161A0CA847ACB718D100B65A1328", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 238
 testRunner.And("Actor expands xDB panel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 239
 testRunner.And("Actor expands Referral section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field values"});
            table23.AddRow(new string[] {
                        "Active"});
            table23.AddRow(new string[] {
                        "Facebook Legal Webinar"});
            table23.AddRow(new string[] {
                        "Online/Social community/Facebook social community"});
#line 240
 testRunner.Then("following information is present in the Campaigns section", ((string)(null)), table23, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Nurture_UC18_Alternate demo path. Twitter campaign. Check personalized info page")]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC18_Alternate demo path. Twitter campaign. Check personalized info page")]
        [Xunit.TraitAttribute("Category", "OnlyManual")]
        public virtual void Nurture_UC18_AlternateDemoPath_TwitterCampaign_CheckPersonalizedInfoPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC18_Alternate demo path. Twitter campaign. Check personalized info page", new string[] {
                        "OnlyManual"});
#line 248
this.ScenarioSetup(scenarioInfo);
#line 249
 testRunner.Given("Twitter website is opened on the https://twitter.com/DSTChase page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 250
 testRunner.When("Actor clicks link with sc_camp=63FEB1E773A0420B9CED034CF07F7D78", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field"});
            table24.AddRow(new string[] {
                        "Email"});
            table24.AddRow(new string[] {
                        "First Name"});
            table24.AddRow(new string[] {
                        "Last Name"});
#line 251
    testRunner.Then("<Taxation Webinar Information> form with following fields is opened", ((string)(null)), table24, "Then ");
#line 256
 testRunner.And("<Send Me Information> button presents on the page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 257
 testRunner.And("image with alt=\"twitter\" presents on the page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Nurture_UC19_Alternate demo path. Twitter campaign. Verify xDB panel")]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC19_Alternate demo path. Twitter campaign. Verify xDB panel")]
        [Xunit.TraitAttribute("Category", "OnlyManual")]
        public virtual void Nurture_UC19_AlternateDemoPath_TwitterCampaign_VerifyXDBPanel()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC19_Alternate demo path. Twitter campaign. Verify xDB panel", new string[] {
                        "OnlyManual"});
#line 261
this.ScenarioSetup(scenarioInfo);
#line 262
 testRunner.Given("Twitter website is opened on the https://twitter.com/DSTChase page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 263
 testRunner.When("Actor clicks link with sc_camp=63FEB1E773A0420B9CED034CF07F7D78", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 264
 testRunner.And("Actor expands xDB panel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 265
 testRunner.And("Actor expands Referral section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field values"});
            table25.AddRow(new string[] {
                        "Active"});
            table25.AddRow(new string[] {
                        "Twitter Legal Webinar"});
            table25.AddRow(new string[] {
                        "Online/Social community/Twitter social community"});
#line 266
 testRunner.Then("following information is present in the Campaigns section", ((string)(null)), table25, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Nurture_UC20_Alternate demo path. Mock-up of a paid search page. Check personaliz" +
            "ed info page")]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC20_Alternate demo path. Mock-up of a paid search page. Check personaliz" +
            "ed info page")]
        [Xunit.TraitAttribute("Category", "Ready")]
        public virtual void Nurture_UC20_AlternateDemoPath_Mock_UpOfAPaidSearchPage_CheckPersonalizedInfoPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC20_Alternate demo path. Mock-up of a paid search page. Check personaliz" +
                    "ed info page", new string[] {
                        "Ready"});
#line 274
this.ScenarioSetup(scenarioInfo);
#line 275
 testRunner.Given("Legal website is opened on the Legal/Search page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 276
 testRunner.When("Actor clicks Chase Ridley Free Legal Webinar link on Search Results", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field"});
            table26.AddRow(new string[] {
                        "Email"});
            table26.AddRow(new string[] {
                        "First Name"});
            table26.AddRow(new string[] {
                        "Last Name"});
#line 277
    testRunner.Then("Taxation Webinar Information form with following fields is opened:", ((string)(null)), table26, "Then ");
#line 282
 testRunner.And("Send Me Information button presents on the page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Nurture_UC21_Alternate demo path. Mock-up of a paid search page. Verify xDB panel" +
            "")]
        [Xunit.TraitAttribute("FeatureTitle", "Nurture")]
        [Xunit.TraitAttribute("Description", "Nurture_UC21_Alternate demo path. Mock-up of a paid search page. Verify xDB panel" +
            "")]
        [Xunit.TraitAttribute("Category", "Ready")]
        public virtual void Nurture_UC21_AlternateDemoPath_Mock_UpOfAPaidSearchPage_VerifyXDBPanel()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nurture_UC21_Alternate demo path. Mock-up of a paid search page. Verify xDB panel" +
                    "", new string[] {
                        "Ready"});
#line 287
this.ScenarioSetup(scenarioInfo);
#line 288
 testRunner.Given("Legal website is opened on the Legal/Search page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 289
 testRunner.When("Actor clicks Chase Ridley Free Legal Webinar link on Search Results", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 290
 testRunner.And("Actor selects Open visit details panel slidebar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 291
 testRunner.And("Actor expands Referral header on xDB panel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field values"});
            table27.AddRow(new string[] {
                        "Active"});
            table27.AddRow(new string[] {
                        "Search Legal Webinar"});
            table27.AddRow(new string[] {
                        "Online/Paid search/Google ads"});
#line 292
 testRunner.Then("Following information is present in the Campaigns section:", ((string)(null)), table27, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                NurtureFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                NurtureFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
